version: "3.8"

services:
  clickhouse-server:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-dev
    ports:
      - "8123:8123" # HTTP interface (needed by clickhouse_connect browser, clients)
      - "9000:9000" # Native TCP interface
    volumes:
      - ./data/clickhouse:/var/lib/clickhouse
    environment:
      - CLICKHOUSE_DB=benchmaker
      - CLICKHOUSE_USER=admin
      - CLICKHOUSE_PASSWORD=admin123
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-transform-test.yaml"]
    volumes:
      - ../docker/admin_server/otel-collector/otel-collector-transform-test.yaml:/etc/otel-collector-transform-test.yaml
      - ../docker/admin_server/otel-collector/logs:/otel-collector/logs

    ports:
      - "4318:4318" # OTLP HTTP
